import { Job, JobBadge } from "../types";

const jobs: Job[] = [
  {
    id: "1",
    logo: "https://placehold.co/48x48?text=Logo",
    company: "TechNova",
    position: "Frontend Developer",
    applicants: 12,
    badges: [
      { type: "experience", value: "Intermediate" },
      { type: "jobType", value: "Full-time" },
      { type: "nature", value: "Remote" },
    ],
    description:
      "Join our team to build modern web apps. We are looking for a passionate developer who loves working with the latest technologies and frameworks. You will collaborate with designers, backend engineers, and product managers to deliver high-quality user experiences. Our projects span multiple industries and require creative problem-solving, attention to detail, and a drive for excellence. You will have the opportunity to learn, grow, and make a real impact. We value teamwork, innovation, and continuous improvement. If you are ready to take your frontend skills to the next level, apply now! ",
    price: "$40/hr",
    postedDate: Date.now(), // today
    posted: "Posted today",
    founded: "2012",
    location: "Remote",
    rating: 4.7,
    reviewCount: 12,
    amountBudget: "$1,400 - $2,000",
    deliveryPeriod: "2-4 weeks",
    services: ["Web Development", "UI/UX Design", "Consulting"],
  },
  {
    qualifications: [
      "Bachelor's degree in Computer Science",
      "2+ years experience in frontend development",
      "Proficiency in React and JavaScript",
    ],
    responsibilities: [
      "Develop and maintain web applications",
      "Collaborate with designers and backend developers",
      "Write clean, scalable code",
    ],
    skills: ["React", "JavaScript", "CSS", "HTML", "Git"],
    id: "2",
    logo: "https://placehold.co/48x48?text=Logo",
    company: "Cloudify",
    position: "Backend Developer",
    applicants: 8,
    badges: [
      { type: "experience", value: "Expert" },
      { type: "jobType", value: "Part-time" },
      { type: "nature", value: "Remote" },
    ],
    description:
      "Work on scalable backend systems. You will be responsible for designing, implementing, and maintaining APIs, databases, and server-side logic. Our ideal candidate is experienced in cloud platforms, microservices, and security best practices. You will work closely with frontend developers and DevOps engineers to ensure seamless integration and deployment. We offer a dynamic environment where you can experiment, optimize, and deliver robust solutions. Join us to build the backbone of modern applications and drive business success. ",
    price: "$55/hr",
    postedDate: Date.now() - 1 * 24 * 60 * 60 * 1000, // 1 day ago
    posted: "Posted 1 day ago",
    founded: "2015",
    location: "Remote",
    rating: 4.6,
    reviewCount: 8,
    amountBudget: "$2,000 - $3,000",
    deliveryPeriod: "3-5 weeks",
    services: ["Backend Development", "Cloud Solutions", "API Integration"],
  },
  {
    qualifications: [
      "Bachelor's degree in Computer Science",
      "3+ years experience in backend development",
      "Familiarity with Node.js and Express",
    ],
    responsibilities: [
      "Design and implement APIs",
      "Maintain database systems",
      "Collaborate with frontend developers",
    ],
    skills: ["Node.js", "Express", "MongoDB", "RESTful APIs", "Git"],
    id: "3",
    logo: "https://placehold.co/48x48?text=Logo",
    company: "DataWorks",
    position: "Data Scientist",
    applicants: 15,
    badges: [
      { type: "experience", value: "Intermediate" },
      { type: "jobType", value: "Contract" },
      { type: "nature", value: "Remote" },
    ],
    description:
      "Analyze data and build ML models. You will work with large datasets, develop predictive models, and communicate insights to stakeholders. Our team values curiosity, rigor, and a passion for data-driven decision making. You will collaborate with engineers and analysts to deploy models in production and monitor their performance. We encourage innovation and provide resources for continuous learning. If you love solving complex problems and making sense of data, this is the role for you. ",
    price: "$60/hr",
    postedDate: Date.now() - 5 * 24 * 60 * 60 * 1000, // 5 days ago
    posted: "Posted 5 days ago",
    founded: "2018",
    location: "Remote",
    rating: 4.8,
    reviewCount: 15,
    amountBudget: "$3,000 - $5,000",
    deliveryPeriod: "4-6 weeks",
    services: ["Data Science", "Machine Learning", "Analytics"],
  },
  {
    qualifications: [
      "Master's degree in Data Science or related field",
      "2+ years experience in data analysis",
      "Strong knowledge of Python and R",
    ],
    responsibilities: [
      "Analyze data and create reports",
      "Develop machine learning models",
      "Collaborate with stakeholders to understand data needs",
    ],
    skills: ["Python", "R", "SQL", "Machine Learning", "Data Visualization"],
    id: "2",
    logo: "https://placehold.co/48x48?text=Logo",
    company: "Cloudify",
    position: "Backend Developer",
    applicants: 8,
    badges: [
      { type: "experience", value: "Expert" },
      { type: "jobType", value: "Part-time" },
      { type: "nature", value: "Remote" },
    ],
    description:
      "Work on scalable backend systems. You will be responsible for designing, implementing, and maintaining APIs, databases, and server-side logic. Our ideal candidate is experienced in cloud platforms, microservices, and security best practices. You will work closely with frontend developers and DevOps engineers to ensure seamless integration and deployment. We offer a dynamic environment where you can experiment, optimize, and deliver robust solutions. Join us to build the backbone of modern applications and drive business success. ",
    price: "$55/hr",
    postedDate: Date.now() - 1 * 24 * 60 * 60 * 1000, // 1 day ago
    posted: "Posted 1 day ago",
  },
  {
    id: "4",
    logo: "https://placehold.co/48x48?text=Logo",
    company: "WebGen",
    position: "UI/UX Designer",
    applicants: 5,
    badges: [
      { type: "experience", value: "Expert" },
      { type: "jobType", value: "Contract" },
      { type: "nature", value: "Remote" },
    ],
    qualifications: [
      "Bachelor's degree in Design or related field",
      "3+ years experience in UI/UX design",
      "Strong portfolio of design work",
    ],
    responsibilities: [
      "Create wireframes and prototypes",
      "Conduct user research",
      "Collaborate with cross-functional teams",
    ],
    skills: ["Figma", "Adobe XD", "Sketch", "User Research", "Prototyping"],
    description:
      "Design user interfaces and experiences. You will create wireframes, prototypes, and visual designs that engage and inspire users. Our team values empathy, creativity, and a deep understanding of user needs. You will collaborate with developers and product managers to bring ideas to life and iterate based on feedback. We offer a supportive environment for growth and experimentation. If you are passionate about design and want to shape the future of digital products, apply now! ",
    price: "$50/hr",
    postedDate: Date.now() - 20 * 24 * 60 * 60 * 1000, // 20 days ago
    posted: "Posted 20 days ago",
    founded: "2010",
    location: "Remote",
    rating: 4.9,
    reviewCount: 5,
    amountBudget: "$2,500 - $4,000",
    deliveryPeriod: "2-3 weeks",
    services: ["UI/UX Design", "Branding", "Web Design"],
  },
  {
    id: "5",
    logo: "https://placehold.co/48x48?text=Logo",
    company: "SecureIT",
    position: "Security Analyst",
    applicants: 7,
    badges: [
      { type: "experience", value: "Intermediate" },
      { type: "jobType", value: "Full-time" },
      { type: "nature", value: "Remote" },
    ],
    qualifications: [
      "Bachelor's degree in Cybersecurity or related field",
      "2+ years experience in security analysis",
      "Knowledge of security frameworks",
    ],
    responsibilities: [
      "Monitor security systems",
      "Conduct risk assessments",
      "Implement security measures",
    ],
    skills: [
      "Security Analysis",
      "Risk Management",
      "Incident Response",
      "Compliance",
      "Network Security",
    ],
    description:
      "Monitor and improve security systems. You will assess risks, implement controls, and respond to incidents to protect our data and infrastructure. Our ideal candidate is detail-oriented, analytical, and proactive. You will work with IT, engineering, and compliance teams to ensure best practices and regulatory requirements are met. We offer opportunities for professional development and certification. If you are committed to security and want to make a difference, join our team! ",
    price: "$45/hr",
    postedDate: Date.now() - 40 * 24 * 60 * 60 * 1000, // 40 days ago
    posted: "Posted 40 days ago",
    founded: "2014",
    location: "Remote",
    rating: 4.5,
    reviewCount: 7,
    amountBudget: "$1,800 - $2,500",
    deliveryPeriod: "3-4 weeks",
    services: ["Security Analysis", "Compliance", "Risk Assessment"],
  },
  {
    id: "6",
    logo: "https://placehold.co/48x48?text=Logo",
    company: "DevOpsPro",
    position: "DevOps Engineer",
    applicants: 18,
    badges: [
      { type: "experience", value: "Expert" },
      { type: "jobType", value: "Full-time" },
      { type: "nature", value: "Remote" },
    ],
    qualifications: [
      "Bachelor's degree in Computer Science or related field",
      "3+ years experience in DevOps",
      "Familiarity with cloud platforms",
    ],
    responsibilities: [
      "Build and maintain CI/CD pipelines",
      "Manage cloud infrastructure",
      "Collaborate with development teams",
    ],
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD", "Git"],
    description:
      "Automate and optimize deployment pipelines. You will build CI/CD workflows, manage cloud infrastructure, and support development teams in delivering software efficiently. Our environment is fast-paced and collaborative, with a focus on reliability and scalability. You will have the chance to work with cutting-edge tools and technologies. If you are passionate about DevOps and want to drive operational excellence, we want to hear from you! ",
    price: "$65/hr",
    postedDate: Date.now() - 90 * 24 * 60 * 60 * 1000, // 90 days ago
    posted: "Posted 90 days ago",
    founded: "2016",
    location: "Remote",
    rating: 4.4,
    reviewCount: 18,
    amountBudget: "$2,200 - $3,500",
    deliveryPeriod: "4-5 weeks",
    services: ["DevOps", "Cloud Infrastructure", "CI/CD"],
  },
  {
    id: "7",
    logo: "https://placehold.co/48x48?text=Logo",
    company: "AI Labs",
    position: "AI Engineer",
    applicants: 22,
    badges: [
      { type: "experience", value: "Intermediate" },
      { type: "jobType", value: "Full-time" },
      { type: "nature", value: "Remote" },
    ],
    qualifications: [
      "Master's degree in AI or related field",
      "3+ years experience in AI development",
      "Strong programming skills in Python",
    ],
    responsibilities: [
      "Develop AI algorithms",
      "Train machine learning models",
      "Collaborate with cross-functional teams",
    ],
    skills: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Machine Learning",
      "Data Analysis",
    ],
    description:
      "Build and deploy AI solutions. You will develop algorithms, train models, and integrate AI into products and services. Our team values innovation, experimentation, and a strong foundation in machine learning. You will collaborate with engineers, researchers, and business leaders to solve real-world problems. We provide resources for research and development, and encourage continuous learning. If you are excited about AI and want to shape the future, apply today! ",
    price: "$70/hr",
    postedDate: Date.now() - 200 * 24 * 60 * 60 * 1000, // 200 days ago
    posted: "Posted 200 days ago",
    founded: "2019",
    location: "Remote",
    rating: 4.9,
    reviewCount: 22,
    amountBudget: "$5,000 - $8,000",
    deliveryPeriod: "6-8 weeks",
    services: ["AI Engineering", "Machine Learning", "Research"],
  },
];

export default jobs;
