export interface ProfileCompletionSkills {
	name: string;
	subs: string[];
}

export const profileCompletionsSkills: ProfileCompletionSkills[] = [
	{
		name: "Graphic Design",
		subs: [
			"Logo Design",
			"Brand Identity Design",
			"Print Design",
			"Packaging Design",
			"Business Card & Stationery",
			"Infographic Design",
			"Poster & Flyer Design",
			"Brochure Design",
			"Social Media Graphics",
			"Presentation Design",
			"T-shirt & Merchandise Design",
			"Label Design",
			"Menu Design",
			"Book & Magazine Layout",
			"Signage Design",
		],
	},
	{
		name: "UI/UX Design",
		subs: [
			"Website UI Design",
			"Mobile App UI Design",
			"Web App UI Design",
			"UX Research & User Flow",
			"Wireframing",
			"Prototyping (Low & High Fidelity)",
			"Dashboard & Admin Panel UI",
			"Landing Page Design",
			"Design System & Style Guide",
			"UI Audit & Redesign",
		],
	},
	{
		name: "Web Development",
		subs: [
			"Front-End Development",
			"Back-End Development",
			"Full-Stack Development",
			"E-commerce Development",
			"Web App Development",
			"Landing Page Development",
			"CMS Development",
			"Custom Website Development",
			"API Integration & Development",
			"Website Maintenance & Support",
			"Responsive Web Development",
			"Web Hosting Setup & Deployment",
			"Website Performance Optimization",
		],
	},
	{
		name: "Mobile App Development",
		subs: [
			"Android App Development",
			"iOS App Development",
			"Cross-Platform App Development",
			"Hybrid App Development",
			"Flutter App Development",
			"React Native App Development",
			"Mobile Game Development",
			"App UI/UX Design",
			"App Maintenance & Support",
			"App Store Optimization (ASO)",
			"Wearable App Development",
			"MVP Development for Mobile Apps",
			"Mobile App Testing & QA",
		],
	},
	{
		name: "Programming & Tech",
		subs: [
			"Software Development",
			"Scripts & Automation",
			"API Development & Integration",
			"Desktop Application Development",
			"Blockchain Development",
			"AI & Machine Learning",
			"Chatbot Development",
			"Cybersecurity & Data Protection",
			"DevOps & Cloud Computing",
			"Database Development & Management",
			"Tech Support & IT Consulting",
			"QA & Software Testing",
			"CRM Development & Customization",
			"ERP Development",
			"IoT Development",
			"Embedded Systems Development",
		],
	},
	{
		name: "Video Editing & Animation",
		subs: [
			"Video Editing",
			"Motion Graphics",
			"2D Animation",
			"3D Animation",
			"Explainer Videos",
			"Whiteboard Animation",
			"Video Ads & Promos",
			"Logo Animation",
			"Intros & Outros",
			"Social Media Video Content",
			"Subtitling & Captioning",
			"Visual Effects (VFX)",
			"Animated Presentations",
			"Slideshow Videos",
			"Cinematic Video Editing",
			"Music Video Editing",
			"Product Video Editing",
		],
	},
	{
		name: "Social Media Design & Management",
		subs: [
			"Instagram Posts & Stories",
			"Facebook Ads Design",
			"Social Media Banners",
			"Content Calendar Creation",
		],
	},
	{
		name: "Presentation Design",
		subs: [
			"Pitch Decks",
			"Investor Presentations",
			"Company Profiles",
			"Pitch Deck Design",
			"Business Presentation",
			"Educational Presentation",
			"Product or Service Showcase",
			"Sales and Marketing Deck",
			"Investor Presentation",
			"Motion/Animated Presentations",
			"Custom Slide Templates",
			"Presentation Redesign",
			"Infographic Presentations",
		],
	},
	{
		name: "Illustration & Digital Art",
		subs: [
			"Character Illustration",
			"Children's Book Illustration",
			"Concept Art",
			"Portrait Illustration",
			"Digital Painting",
			"Vector Art",
			"Comic & Manga Art",
			"Game Art",
			"Isometric Illustrations",
			"Editorial Illustration",
			"NFT Art Creation",
			"Fashion Illustration",
			"Mascot Design",
			"Storyboard Illustration",
			"Mixed Media Art",
		],
	},
];
