name: Deploy React+Vite App to server for learning
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./apps/learning

    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy files via SFTP
        uses: wlixcc/SFTP-Deploy-action@v1.2.4
        with:
          server: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          local_path: './apps/main/learning/*'
          remote_path: '/var/www/learn/'
