name: 🚀 Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Package build
        run: tar -czf nextjs-app.tar.gz src .gitignore README.md eslint.config.js index.html package-lock.json package.json vite.config.js

      - name: Upload build to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "nextjs-app.tar.gz"
          target: "~/app/nextjs-app.tar.gz"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/app
            rm -rf .next
            tar -xzf nextjs-app.tar.gz
            rm nextjs-app.tar.gz
            npm ci --omit=dev
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- run start -- -p 3000
            pm2 save
